spring:
  task:
    scheduling:
      enabled: false
  jackson:
    time-zone: America/Lima
    serialization:
      write-dates-as-timestamps: false
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    validate-on-migrate: true

logging:
  level:
    root: WARN
    com.playzone.pems: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: WARN

server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 2048
    
  error:
    include-message: never
    include-binding-errors: never

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

