package com.playzone.pems.infrastructure.persistence.preferencia.mapper;

import com.playzone.pems.domain.preferencia.model.PreferenciaAdmin;
import com.playzone.pems.infrastructure.persistence.preferencia.entity.PreferenciaAdminEntity;
import com.playzone.pems.infrastructure.persistence.usuario.entity.UsuarioAdminEntity;
import org.springframework.stereotype.Component;

@Component
public class PreferenciaAdminMapper {

    public PreferenciaAdmin toDomain(PreferenciaAdminEntity e) {
        if (e == null) return null;
        return PreferenciaAdmin.builder()
                .id(e.getId())
                .idUsuarioAdmin(e.getUsuarioAdmin() != null ? e.getUsuarioAdmin().getId() : null)
                .tema(e.getTema())
                .colorPrimario(e.getColorPrimario())
                .colorSecundario(e.getColorSecundario())
                .colorSidebar(e.getColorSidebar())
                .colorAcento(e.getColorAcento())
                .tipografia(e.getTipografia())
                .tamanioFuente(e.getTamanioFuente())
                .radiosBordes(e.getRadiosBordes())
                .sidebarColapsado(e.isSidebarColapsado())
                .sidebarFlotante(e.isSidebarFlotante())
                .modoCompacto(e.isModoCompacto())
                .anchoContenido(e.getAnchoContenido())
                .mostrarMigaspan(e.isMostrarMigaspan())
                .mostrarIconosMenu(e.isMostrarIconosMenu())
                .mostrarAnimaciones(e.isMostrarAnimaciones())
                .animacionSidebar(e.isAnimacionSidebar())
                .hoverEffects(e.isHoverEffects())
                .loadersAnimados(e.isLoadersAnimados())
                .confirmarAcciones(e.isConfirmarAcciones())
                .recordarUltimaPagina(e.isRecordarUltimaPagina())
                .restaurarTabs(e.isRestaurarTabs())
                .autoRefreshDashboard(e.isAutoRefreshDashboard())
                .intervaloRefreshSeg(e.getIntervaloRefreshSeg())
                .dashboardPersonalizado(e.getDashboardPersonalizado())
                .widgetsVisibles(e.getWidgetsVisibles())
                .accesosRapidos(e.getAccesosRapidos())
                .ordenWidgets(e.getOrdenWidgets())
                .layoutDashboard(e.getLayoutDashboard())
                .filtrosPersistentes(e.getFiltrosPersistentes())
                .columnasVisibles(e.getColumnasVisibles())
                .ordenamientoTablas(e.getOrdenamientoTablas())
                .elementosPorTabla(e.getElementosPorTabla())
                .sonidoNotificaciones(e.isSonidoNotificaciones())
                .notificacionesPush(e.isNotificacionesPush())
                .notificacionesEmail(e.isNotificacionesEmail())
                .notificacionesVisuales(e.isNotificacionesVisuales())
                .badgesDinamicos(e.isBadgesDinamicos())
                .idioma(e.getIdioma())
                .zonaHoraria(e.getZonaHoraria())
                .formatoFecha(e.getFormatoFecha())
                .formatoHora(e.getFormatoHora())
                .primerDiaSemana(e.getPrimerDiaSemana())
                .altoContraste(e.isAltoContraste())
                .reducirAnimaciones(e.isReducirAnimaciones())
                .aumentarEspaciado(e.isAumentarEspaciado())
                .cursorGrande(e.isCursorGrande())
                .fechaCreacion(e.getFechaCreacion())
                .fechaActualizacion(e.getFechaActualizacion())
                .build();
    }

    public PreferenciaAdminEntity toEntity(PreferenciaAdmin d, UsuarioAdminEntity usuarioAdmin) {
        return PreferenciaAdminEntity.builder()
                .id(d.getId())
                .usuarioAdmin(usuarioAdmin)
                .tema(d.getTema())
                .colorPrimario(d.getColorPrimario())
                .colorSecundario(d.getColorSecundario())
                .colorSidebar(d.getColorSidebar())
                .colorAcento(d.getColorAcento())
                .tipografia(d.getTipografia())
                .tamanioFuente(d.getTamanioFuente())
                .radiosBordes(d.getRadiosBordes())
                .sidebarColapsado(d.isSidebarColapsado())
                .sidebarFlotante(d.isSidebarFlotante())
                .modoCompacto(d.isModoCompacto())
                .anchoContenido(d.getAnchoContenido())
                .mostrarMigaspan(d.isMostrarMigaspan())
                .mostrarIconosMenu(d.isMostrarIconosMenu())
                .mostrarAnimaciones(d.isMostrarAnimaciones())
                .animacionSidebar(d.isAnimacionSidebar())
                .hoverEffects(d.isHoverEffects())
                .loadersAnimados(d.isLoadersAnimados())
                .confirmarAcciones(d.isConfirmarAcciones())
                .recordarUltimaPagina(d.isRecordarUltimaPagina())
                .restaurarTabs(d.isRestaurarTabs())
                .autoRefreshDashboard(d.isAutoRefreshDashboard())
                .intervaloRefreshSeg(d.getIntervaloRefreshSeg())
                .dashboardPersonalizado(d.getDashboardPersonalizado())
                .widgetsVisibles(d.getWidgetsVisibles())
                .accesosRapidos(d.getAccesosRapidos())
                .ordenWidgets(d.getOrdenWidgets())
                .layoutDashboard(d.getLayoutDashboard())
                .filtrosPersistentes(d.getFiltrosPersistentes())
                .columnasVisibles(d.getColumnasVisibles())
                .ordenamientoTablas(d.getOrdenamientoTablas())
                .elementosPorTabla(d.getElementosPorTabla())
                .sonidoNotificaciones(d.isSonidoNotificaciones())
                .notificacionesPush(d.isNotificacionesPush())
                .notificacionesEmail(d.isNotificacionesEmail())
                .notificacionesVisuales(d.isNotificacionesVisuales())
                .badgesDinamicos(d.isBadgesDinamicos())
                .idioma(d.getIdioma())
                .zonaHoraria(d.getZonaHoraria())
                .formatoFecha(d.getFormatoFecha())
                .formatoHora(d.getFormatoHora())
                .primerDiaSemana(d.getPrimerDiaSemana())
                .altoContraste(d.isAltoContraste())
                .reducirAnimaciones(d.isReducirAnimaciones())
                .aumentarEspaciado(d.isAumentarEspaciado())
                .cursorGrande(d.isCursorGrande())
                .build();
    }
}
