ALTER TABLE tipo_notificacion
    ADD COLUMN IF NOT EXISTS es_obligatoria BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE tipo_notificacion
SET es_obligatoria = TRUE
WHERE codigo = 'LOGIN_IP_NUEVA';


INSERT INTO tipo_notificacion
    (codigo, modulo, nombre, descripcion, destinatario_default, canales_default,
     plantilla_titulo, plantilla_mensaje, prioridad, es_sistema, es_obligatoria, orden)
VALUES

    ('RESERVA_NUEVA',
     'reserva', 'Nueva reserva online', 'Reserva publica recibida en el portal',
     'ADMIN', ARRAY['IN_APP'],
     'Nueva reserva — {cliente}',
     '{cliente} reservo para el {fecha}. Aforo actualizado.',
     'NORMAL', TRUE, FALSE, 100),

    ('RESERVA_CANCELADA_CLIENTE',
     'reserva', 'Reserva cancelada por cliente', 'El cliente cancelo desde su portal',
     'ADMIN', ARRAY['IN_APP'],
     'Reserva cancelada — {cliente}',
     '{cliente} cancelo su reserva del {fecha}.',
     'NORMAL', TRUE, FALSE, 101),

    ('RESERVA_PAGO_VERIFICADO',
     'reserva', 'Pago Yape verificado', 'Comprobante de pago aprobado',
     'ADMIN', ARRAY['IN_APP'],
     'Yape verificado — {cliente}',
     'El comprobante de {cliente} por S/ {monto} fue aprobado.',
     'NORMAL', TRUE, FALSE, 102),

    ('RESERVA_PAGO_RECHAZADO',
     'reserva', 'Pago Yape rechazado', 'Comprobante de pago invalido',
     'ADMIN', ARRAY['IN_APP'],
     'Yape rechazado — {cliente}',
     'El comprobante de {cliente} fue rechazado. El cliente debe volver a intentarlo.',
     'NORMAL', TRUE, FALSE, 103),

    ('AFORO_AGOTADO',
     'reserva', 'Aforo agotado', 'Sin cupos disponibles para la fecha',
     'ADMIN', ARRAY['IN_APP'],
     'Aforo completo — {fecha}',
     'El aforo del {fecha} en {sede} esta completo.',
     'ALTA', TRUE, FALSE, 104),

    ('EVENTO_PRESUPUESTO_SOLICITADO',
     'evento', 'Cotizacion solicitada', 'Cliente solicito cotizacion de evento privado',
     'ADMIN', ARRAY['IN_APP','EMAIL'],
     'Nueva cotizacion — {cliente}',
     '{cliente} solicito una cotizacion para un evento el {fecha}.',
     'ALTA', TRUE, FALSE, 110),

    ('EVENTO_ADELANTO_RECIBIDO',
     'evento', 'Adelanto recibido', 'Pago de adelanto registrado para un evento',
     'ADMIN', ARRAY['IN_APP'],
     'Adelanto registrado — {evento}',
     'Se registro un adelanto de S/ {monto} para el evento de {cliente} el {fecha}.',
     'NORMAL', TRUE, FALSE, 111),

    ('EVENTO_SALDO_RECIBIDO',
     'evento', 'Saldo final recibido', 'Pago de saldo registrado para un evento',
     'ADMIN', ARRAY['IN_APP'],
     'Saldo registrado — {evento}',
     'Se registro el saldo de S/ {monto} para el evento de {cliente}. Evento saldado.',
     'NORMAL', TRUE, FALSE, 112),

    ('EVENTO_CANCELADO_CLIENTE',
     'evento', 'Evento cancelado por cliente', 'Cliente solicito cancelacion del evento privado',
     'ADMIN', ARRAY['IN_APP','EMAIL'],
     'Evento cancelado — {cliente}',
     '{cliente} cancelo el evento privado del {fecha}.',
     'ALTA', TRUE, FALSE, 113),

    ('EVENTO_CHECKLIST_INCOMPLETO',
     'evento', 'Checklist incompleto', 'Evento proximo con checklist sin completar',
     'ADMIN', ARRAY['IN_APP'],
     'Checklist pendiente — {evento}',
     'El evento de {cliente} es en menos de 48 horas y el checklist no esta completo.',
     'ALTA', TRUE, FALSE, 114),

    ('CONTRATO_FIRMADO',
     'evento', 'Contrato firmado', 'El cliente firmo el contrato digital del evento',
     'ADMIN', ARRAY['IN_APP'],
     'Contrato firmado — {cliente}',
     '{cliente} firmo el contrato del evento del {fecha}.',
     'NORMAL', TRUE, FALSE, 115),

    ('CONTRATO_VENCIDO_SIN_FIRMA',
     'evento', 'Contrato sin firma vencido', 'Contrato enviado hace mas de 5 dias sin firma',
     'ADMIN', ARRAY['IN_APP','EMAIL'],
     'Contrato vencido — {cliente}',
     'El contrato de {cliente} para el evento del {fecha} lleva {dias} dias sin firma.',
     'CRITICA', TRUE, TRUE, 116),

    ('CAJA_CIERRE_DISCREPANCIA',
     'caja', 'Discrepancia en cierre de caja', 'Diferencia entre monto esperado y monto contado',
     'ADMIN', ARRAY['IN_APP','EMAIL'],
     'Discrepancia en caja — {sede}',
     'El cierre de caja en {sede} tiene una diferencia de S/ {diferencia}.',
     'ALTA', TRUE, FALSE, 120),

    ('VENTA_MONTO_ALTO',
     'caja', 'Venta de monto elevado', 'Venta en mostrador supera el umbral configurado',
     'ADMIN', ARRAY['IN_APP'],
     'Venta elevada — S/ {monto}',
     'Se registro una venta de S/ {monto} en {sede}.',
     'NORMAL', TRUE, FALSE, 121),

    ('EGRESO_MONTO_ALTO',
     'caja', 'Egreso elevado registrado', 'Egreso de caja supera el umbral configurado',
     'ADMIN', ARRAY['IN_APP'],
     'Egreso elevado — S/ {monto}',
     'Se registro un egreso de S/ {monto} en {sede}.',
     'NORMAL', TRUE, FALSE, 122),

    ('RESUMEN_DIARIO_CAJA',
     'caja', 'Resumen diario de caja', 'Totales del dia al cierre de operaciones',
     'ADMIN', ARRAY['IN_APP','EMAIL'],
     'Resumen del dia — {fecha}',
     'Ingresos: S/ {ingresos}. Egresos: S/ {egresos}. Caja neta: S/ {neto}.',
     'BAJA', TRUE, FALSE, 123),

    ('NOVEDAD_PUBLICADA',
     'cms', 'Novedad publicada', 'Novedad o entrada de blog publicada en el sitio',
     'ADMIN', ARRAY['IN_APP'],
     'Novedad publicada',
     'La novedad "{titulo}" fue publicada exitosamente.',
     'BAJA', TRUE, FALSE, 130),

    ('BANNER_EXPIRADO',
     'cms', 'Banner vencido', 'Banner llego a su fecha de fin y fue desactivado',
     'ADMIN', ARRAY['IN_APP'],
     'Banner vencido — {banner}',
     'El banner "{banner}" vencio y fue desactivado automaticamente.',
     'BAJA', TRUE, FALSE, 131),

    ('PROMOCION_NUEVA_ACTIVA',
     'marketing', 'Promocion activada', 'Promocion entro en vigencia hoy',
     'ADMIN', ARRAY['IN_APP'],
     'Promocion activa — {promocion}',
     'La promocion "{promocion}" entro en vigencia hoy.',
     'BAJA', TRUE, FALSE, 132),

    ('REPORTE_EXPORTACION_LISTA',
     'sistema', 'Exportacion lista', 'Reporte pesado termino de generarse y esta disponible',
     'ADMIN', ARRAY['IN_APP'],
     'Reporte listo para descargar',
     'El reporte "{reporte}" esta listo. Puedes descargarlo desde la seccion de reportes.',
     'BAJA', TRUE, FALSE, 133),

    ('CLIENTE_NUEVO_REGISTRADO',
     'cliente', 'Nuevo cliente registrado', 'Cliente creo una cuenta en el portal publico',
     'ADMIN', ARRAY['IN_APP'],
     'Nuevo cliente — {cliente}',
     '{cliente} se registro en el portal.',
     'BAJA', TRUE, FALSE, 140),

    ('CLIENTE_SIN_ACTIVIDAD',
     'cliente', 'Cliente inactivo', 'Cliente sin reservas ni eventos en mas de 90 dias',
     'ADMIN', ARRAY['IN_APP'],
     'Cliente inactivo — {cliente}',
     '{cliente} no ha realizado reservas en los ultimos {dias} dias.',
     'BAJA', TRUE, FALSE, 141),

    ('ADMIN_CUENTA_BLOQUEADA',
     'sistema', 'Cuenta de admin bloqueada', 'Cuenta bloqueada por demasiados intentos fallidos de login',
     'ADMIN', ARRAY['IN_APP','EMAIL'],
     'Cuenta bloqueada',
     'Tu cuenta fue bloqueada por {intentos} intentos fallidos. Se desbloqueara en {minutos} minutos.',
     'CRITICA', TRUE, TRUE, 142),

    ('ERROR_ENVIO_EMAIL',
     'sistema', 'Fallo en envio de email', 'Email transaccional no pudo enviarse tras 3 intentos',
     'ADMIN', ARRAY['IN_APP'],
     'Fallo en email — {destinatario}',
     'No se pudo enviar el email a {destinatario}. Error: {error}.',
     'ALTA', TRUE, FALSE, 143),

    ('RESERVA_EN_CAJA_HOY',
     'caja', 'Reservas pendientes en caja', 'Reservas con pago presencial pendientes para hoy',
     'CAJERO', ARRAY['IN_APP'],
     'Reservas en caja hoy — {cantidad}',
     'Hay {cantidad} reserva(s) con pago presencial pendiente para hoy.',
     'BAJA', TRUE, FALSE, 150),

    ('VENTA_ANULADA',
     'caja', 'Venta anulada', 'Una venta realizada por el cajero fue anulada',
     'CAJERO', ARRAY['IN_APP'],
     'Venta anulada — #{id}',
     'La venta #{id} de S/ {monto} fue anulada.',
     'NORMAL', TRUE, FALSE, 151),

    ('DESCUENTO_REQUIERE_APROBACION',
     'caja', 'Descuento requiere aprobacion', 'Descuento solicitado supera el limite permitido al cajero',
     'CAJERO', ARRAY['IN_APP'],
     'Descuento pendiente de aprobacion',
     'El descuento del {porcentaje}% en la venta #{id} requiere autorizacion de un administrador.',
     'ALTA', TRUE, FALSE, 152),

    ('TURNO_POR_INICIAR',
     'caja', 'Turno por iniciar', 'El turno del cajero inicia en 30 minutos',
     'CAJERO', ARRAY['IN_APP'],
     'Tu turno inicia en 30 minutos',
     'Tu turno en {sede} inicia a las {hora}. Recuerda abrir la caja al llegar.',
     'BAJA', TRUE, FALSE, 153),

    ('RESERVA_MODIFICADA',
     'reserva', 'Reserva modificada por el local', 'El administrador modifico la fecha u hora de la reserva',
     'CLIENTE', ARRAY['IN_APP','EMAIL'],
     'Tu reserva fue modificada',
     'Tu reserva fue cambiada al {fecha}. Si tienes dudas, contacta con nosotros.',
     'NORMAL', TRUE, FALSE, 160),

    ('PAGO_CONFIRMADO',
     'reserva', 'Pago confirmado', 'El comprobante Yape del cliente fue aprobado',
     'CLIENTE', ARRAY['IN_APP','EMAIL'],
     'Pago confirmado — S/ {monto}',
     'Tu pago de S/ {monto} fue verificado y aprobado. Tu reserva esta confirmada.',
     'NORMAL', TRUE, FALSE, 161),

    ('PAGO_RECHAZADO',
     'reserva', 'Pago rechazado', 'El comprobante Yape del cliente fue rechazado',
     'CLIENTE', ARRAY['IN_APP','EMAIL'],
     'Pago rechazado',
     'Tu comprobante no pudo verificarse. Por favor intenta con otro metodo de pago o contacta con nosotros.',
     'ALTA', TRUE, TRUE, 162),

    ('TICKET_DISPONIBLE',
     'reserva', 'Tickets disponibles para descargar', 'Las entradas del cliente estan listas',
     'CLIENTE', ARRAY['IN_APP','EMAIL'],
     'Tus entradas estan listas',
     'Tus entradas para el {fecha} en {sede} estan disponibles. Descargalas desde tu portal.',
     'NORMAL', TRUE, FALSE, 163),

    ('EVENTO_CONTRATO_LISTO',
     'evento', 'Contrato listo para firmar', 'El administrador subio el contrato al sistema',
     'CLIENTE', ARRAY['IN_APP','EMAIL'],
     'Contrato listo — {evento}',
     'Tu contrato para el evento del {fecha} esta listo. Ingresa a tu portal para firmarlo.',
     'ALTA', TRUE, FALSE, 170),

    ('EVENTO_PRESUPUESTO_ENVIADO',
     'evento', 'Cotizacion recibida', 'El administrador envio la cotizacion al cliente',
     'CLIENTE', ARRAY['IN_APP','EMAIL'],
     'Tu cotizacion esta lista',
     'Hemos preparado tu cotizacion para el evento del {fecha}. Revisala en tu portal.',
     'NORMAL', TRUE, FALSE, 171),

    ('EVENTO_CANCELADO_ADMIN',
     'evento', 'Evento cancelado por el local', 'El administrador cancelo el evento del cliente',
     'CLIENTE', ARRAY['IN_APP','EMAIL'],
     'Tu evento fue cancelado',
     'Lamentamos informarte que tu evento del {fecha} fue cancelado. Motivo: {motivo}. Nos comunicaremos contigo.',
     'ALTA', TRUE, TRUE, 172),

    ('EVENTO_RECORDATORIO_3DIAS',
     'evento', 'Tu evento es en 3 dias', 'Recordatorio anticipado 3 dias antes del evento',
     'CLIENTE', ARRAY['IN_APP','EMAIL'],
     'Tu evento es el {fecha}',
     'Tu evento privado en {sede} es en 3 dias. Si tienes alguna consulta, estamos aqui para ayudarte.',
     'NORMAL', TRUE, FALSE, 173),

    ('PAGO_ADELANTO_CONFIRMADO',
     'evento', 'Adelanto registrado', 'El administrador registro el pago de adelanto del evento',
     'CLIENTE', ARRAY['IN_APP','EMAIL'],
     'Adelanto confirmado — S/ {monto}',
     'Tu adelanto de S/ {monto} para el evento del {fecha} fue registrado exitosamente.',
     'NORMAL', TRUE, FALSE, 174),

    ('DOCUMENTO_LISTO',
     'venta', 'Comprobante disponible', 'La factura o boleta del cliente esta generada',
     'CLIENTE', ARRAY['IN_APP','EMAIL'],
     'Tu comprobante esta disponible',
     'Tu {tipo_comprobante} N° {numero} por S/ {monto} esta disponible para descargar.',
     'BAJA', TRUE, FALSE, 180),

    ('PUNTOS_ACUMULADOS',
     'cliente', 'Puntos acumulados', 'El cliente acumulo puntos de fidelizacion en su compra',
     'CLIENTE', ARRAY['IN_APP'],
     'Ganaste {puntos} puntos',
     'Acumulaste {puntos} puntos en tu ultima compra. Total acumulado: {total} puntos.',
     'BAJA', TRUE, FALSE, 190),

    ('PUNTOS_POR_VENCER',
     'cliente', 'Puntos proximos a vencer', 'Los puntos del cliente vencen en menos de 30 dias',
     'CLIENTE', ARRAY['IN_APP','EMAIL'],
     'Tus puntos vencen pronto',
     'Tienes {puntos} puntos que vencen el {fecha}. Usaos en tu proxima visita.',
     'NORMAL', TRUE, FALSE, 191),

    ('PROMOCION_EXCLUSIVA',
     'marketing', 'Promocion especial para ti', 'Promocion de marketing segmentado para el cliente',
     'CLIENTE', ARRAY['IN_APP','EMAIL'],
     '{nombre_promo}',
     '{descripcion_promo} Valida hasta el {fecha_fin}.',
     'BAJA', TRUE, FALSE, 192),

    ('PASSWORD_CAMBIADO',
     'sistema', 'Contrasena cambiada', 'El cliente cambio su contrasena exitosamente',
     'CLIENTE', ARRAY['EMAIL'],
     'Tu contrasena fue cambiada',
     'Tu contrasena se cambio el {fecha}. Si no fuiste tu, contacta con nosotros de inmediato.',
     'CRITICA', TRUE, TRUE, 200),

    ('RESENA_RESPONDIDA',
     'sitio', 'El local respondio tu resena', 'El administrador respondio la resena del cliente',
     'CLIENTE', ARRAY['IN_APP','EMAIL'],
     'Respondieron tu resena',
     'Hemos respondido tu comentario. Ingresa al sitio para verlo.',
     'BAJA', TRUE, FALSE, 201);
